#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
diff-editor = "meld-3"
diff-formatter = ":git"
show-cryptographic-signatures = false
default-command = "log"

[user]
name = "Techcable"
email = "git@techcable.net"

[signing]
backend = "gpg"
behavior = "own"

[fsmonitor]
# This is not enabled globally because on macOS
# it means each repo needs several seconds to startup
# backend = "watchman"
